{% set name = "runthis-server" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/runthis-server/releases/download/{{ version }}/runthis-server-{{ version }}.tar.gz
  sha256: 2d1cfadaf09b2e5121ac7965613a21fe8f0e7484a1a7b5a3ecdb5b88c707cc3e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - runthis-server = runthis.server.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ruamel.yaml
    - quart

test:
  imports:
    - runthis.server
  commands:
    - runthis-server --help

about:
  home: https://github.com/regro/runthis-server
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'xterm server for runthis project'

extra:
  recipe-maintainers:
    - scopatz
