{% set name = "runthis-server" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/runthis-server/releases/download/{{ version }}/runthis-server-{{ version }}.tar.gz
  sha256: 15edb6867c4376674e7a94af1de0d568f481f81bc3e210891a3740f8a5a05e0e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - runthis-server = runthis.server.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ruamel.yaml
    - quart

test:
  imports:
    - runthis.server
  commands:
    - runthis-server --help

about:
  home: https://github.com/regro/runthis-server
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'xterm server for runthis project'

extra:
  recipe-maintainers:
    - scopatz
